name: Build ISO (ROCm)

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: "docker_imgcache,docker_buildkit,docker_imgcache"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --privileged --volume ${{ github.workspace }}:/workspace
          run: |
            # Exit on error
            set -eu

            # Install dependencies
            .ci/dependencies.sh

            # Patch mkarchiso
            .ci/mkarchiso.sh

            # Configure to use ROCm
            pushd /workspace
              .ci/configure.py rocm
            popd

            # Build image
            mkarchiso -v -m iso -w /workspace/work -o /workspace/out /workspace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archiso-output
          path: out/
