name: Build ISO on hosted runner (CUDA, empty)

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest

          options: --privileged --volume ${{ github.workspace }}:/workspace
          run: |
            # Exit on error
            set -eu

            # Enter project directory
            pushd /workspace
              # Install dependencies
              .ci/dependencies.sh

              # Patch mkarchiso
              .ci/mkarchiso.sh

              # Remove repositories
              .ci/empty.sh

              # Configure to use CUDA
              .ci/configure.py cuda empty
            popd

            # Build image
            mkarchiso -v -m iso -w /_work -o /workspace/out /workspace

      - name: Create summary
        run: |
          # Exit on error
          set -eu

          # Start code section
          echo '`' > "$GITHUB_STEP_SUMMARY"

          # Print checksums
          sha256sum out/* | sed 's/out\///' >> "$GITHUB_STEP_SUMMARY"

          # End code section
          echo '`' >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archiso-output
          path: out/