name: Build ISO on selfhosted runner (ROCm)

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --privileged --volume ${{ github.workspace }}:/workspace
          run: |
            # Exit on error
            set -eu

            # Enter project directory
            pushd /workspace
              # Install dependencies
              .ci/dependencies.sh

              # Patch mkarchiso
              .ci/mkarchiso.sh

              # Configure to use ROCm
              .ci/configure.py rocm
            popd

            # Build image
            mkarchiso -v -m iso -w /_work -o /workspace/out /workspace

      - name: Create summary
        run: |
          # Exit on error
          set -eu

          # Print checksums to summary
          sha256sum out/* > "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archiso-output
          path: out/