name: Do nothing on selfhosted runner

on:
  schedule:
    - cron: "30 1 1,15 * *"

  workflow_dispatch:

jobs:
  vm-start:
    runs-on: ubuntu-latest

    steps:
      - name: Save ssh configuration
        run: |
          # Create ssh directory
          mkdir ~/.ssh

          # Save ssh config
          echo "${{ secrets.SSH_CONFIG }}" | base64 -d > ~/.ssh/config

          # Save ssh known hosts
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" | base64 -d > ~/.ssh/known_hosts

          # Save ssh private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > /tmp/private.key

          # Fix permissions for private key
          chmod 600 /tmp/private.key

      - name: Start Github Actions Runner VM
        run: |
          status=$(ssh runner "virsh domstate GithubActions")

          if [ "$status" = "shutoff" ]; then
            ssh runner "virsh start GithubActions"
            echo "started=true" >> "$GITHUB_OUTPUT"
          else
            echo "started=false" >> "$GITHUB_OUTPUT"
          fi

  do-nothing:
    if: ${{ needs.vm-start.outputs.started == 'true' }}
    needs: vm-start
    runs-on: self-hosted

    steps:
      - name: Do nothing
        run: |
          true

  vm-stop:
    if: ${{ needs.vm-start.outputs.started == 'true' }}
    needs: do-nothing
    runs-on: ubuntu-latest

    steps:
      - name: Save ssh configuration
        run: |
          # Create ssh directory
          mkdir ~/.ssh

          # Save ssh config
          echo "${{ secrets.SSH_CONFIG }}" | base64 -d > ~/.ssh/config

          # Save ssh known hosts
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" | base64 -d > ~/.ssh/known_hosts

          # Save ssh private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > /tmp/private.key

          # Fix permissions for private key
          chmod 600 /tmp/private.key

      - name: Stop Github Actions Runner VM
        run: |
          # Invoke regular shutdown
          ssh runner "virsh shutdown GithubActions"
